### ISSUE TITLE
Interaction between nosetests and capturer

### ISSUE THREAD

**Issue by artgoldberg** [vforgione/log#6]
If nosetests is used to run the tests under python 3, curious behavior arises.
`nosetests-3.4 tests/test_loggers.py` generates 16 errors of the form:
```
ERROR: test_using_and_only (test_loggers.WithLoggerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arthur_at_sinai/gitOnMyLaptopLocal/log/tests/test_loggers.py", line 237, in test_using_and_only
    with CaptureOutput() as co:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/capturer/__init__.py", line 157, in __init__
    self.stdout_stream = self.initialize_stream(sys.stdout, STDOUT_FD)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/capturer/__init__.py", line 191, in initialize_stream
    real_fd = file_obj.fileno()
io.UnsupportedOperation: fileno
```
However, the errors are neither test failures nor bugs in the testing code. Rather, they reflect an interaction between nosetests and capturer. To demonstrate this, try 
`nosetests-3.4 --nocapture tests/test_loggers.py`. It generates no errors, but produces some humorous output:
```
..e48bd8e5-2c23-4c59-b00e-8679965d387d message
.heavy message
.2016-09-24T14:27:02.216323 | INFO | log.loggers | stuff | /Users/arthur_at_sinai/gitOnMyLaptopLocal/log/tests/test_loggers.py | 256 | test_use_all_the_reserved_keys | 8895
.uno message
dos messages
.[2016-09-24T13:27:02.273533-05:00] [DEBUG] : message
.[2016-09-24T13:27:02.304046-05:00] [ERROR] : message
.[2016-09-24T13:27:02.340112-05:00] [EXCEPTION] : message
Traceback (most recent call last):
  File "/Users/arthur_at_sinai/gitOnMyLaptopLocal/log/tests/test_loggers.py", line 52, in test_exception
    1 / 0
ZeroDivisionError: division by zero
.[2016-09-24T13:27:02.376473-05:00] [INFO] : message
.[2016-09-24T13:27:02.409575-05:00] [WARNING] : message
.[2016-09-24T13:27:02.445607-05:00] [DEBUG] : message
.[2016-09-24T13:27:02.479447-05:00] [ERROR] : message
.[2016-09-24T13:27:02.517676-05:00] [EXCEPTION] : message
Traceback (most recent call last):
  File "/Users/arthur_at_sinai/gitOnMyLaptopLocal/log/tests/test_loggers.py", line 52, in test_exception
    1 / 0
ZeroDivisionError: division by zero
.[2016-09-24T13:27:02.549882-05:00] [INFO] : message
.[2016-09-24T13:27:02.585171-05:00] [WARNING] : message
.........[2016-09-24T13:27:02.619721-05:00] [INFO] : message
[2016-09-24T13:27:02.619721-05:00] [INFO] : message
[2016-09-24T13:27:02.653760-05:00] [INFO] : there can be only one
[2016-09-24T13:27:02.687796-05:00] [INFO] : again! again!
[2016-09-24T13:27:02.720013-05:00] [INFO] : message
[2016-09-24T13:27:02.720013-05:00] [INFO] : message
[2016-09-24T13:27:02.757611-05:00] [INFO] : again! again!
[2016-09-24T13:27:02.757611-05:00] [INFO] : again! again!
.[2016-09-24T13:27:02.790992-05:00] [INFO] : message
[2016-09-24T13:27:02.825909-05:00] [INFO] : yay!
check this out: huzzah!
check this out: awwww yeah!
```
It would be nice to have `nosetests-3.4 tests/test_loggers.py` work without errors, but I don't have time to investigate this further now.
Arthur

**Comment by vforgione** [comment]
Why are you using `nose`? All the testing and configuration in this project uses `py.test`. For the exact reason you specified, I chose to use pytest over nose because it doesn't produce false positives. 

My experience with using nose is that it is poorly built, has on many occasions produced unstable results and has lost most, of not all, of the community in favor of pytest.

I will not make changes to the tests to satisfy nose.

**Comment by artgoldberg** [comment]
Thanks for your feedback, Vince. We'll investigate test runners other than nose.
Arthur
